# bt-brain — first-time install (member-side)
# Run from the cloned repo root:  powershell -ExecutionPolicy Bypass -File .brain\install.ps1
# Optional params skip the prompts (also lets Claude Code run this unattended):
#   .brain\install.ps1 -Name Alex -FullName "Alex Lim" -Email alex@example.com
# PS 5.1 compatible. Idempotent: safe to re-run; never overwrites existing personal files.

param(
    [string]$Name,
    [string]$FullName,
    [string]$Email
)

$ErrorActionPreference = "Stop"

# --- locate repo root (folder containing Brain/README.md) ---
$root = Split-Path -Parent $PSScriptRoot
if (-not (Test-Path (Join-Path $root "Brain\README.md"))) {
    throw "Run this from the cloned vault repo (Brain/README.md not found at $root)."
}
Set-Location $root

# --- parse manifest ---
$manifest = Join-Path $PSScriptRoot "manifest.yml"
$enginePaths = @()
foreach ($line in Get-Content $manifest) {
    if ($line -match '^\s+"([^"]+)":\s+(locked|contributable)\s*$') {
        $enginePaths += $Matches[1]
    }
}
if ($enginePaths.Count -eq 0) { throw "No engine paths parsed from manifest.yml - aborting." }

# --- generate .gitignore (whitelist: everything ignored unless engine) ---
$rules = New-Object System.Collections.Generic.List[string]
$rules.Add("# GENERATED by .brain/install.ps1 from .brain/manifest.yml - do not edit by hand.")
$rules.Add("# Whitelist: everything is invisible to git except engine paths.")
$rules.Add("/*")
$groups = $enginePaths | Group-Object { ($_ -split '/')[0] }
foreach ($g in $groups) {
    $top = $g.Name
    $rules.Add("!/$top")
    $wholeTop = $false
    foreach ($p in $g.Group) { if ($p -eq $top) { $wholeTop = $true } }
    if (-not $wholeTop) {
        $rules.Add("/$top/*")
        foreach ($p in $g.Group) {
            $child = $p.Substring($top.Length + 1)
            $rules.Add("!/$top/$child")
        }
    }
}
Set-Content -Path (Join-Path $root ".gitignore") -Value ($rules -join "`n") -Encoding utf8
Write-Host "[ok] .gitignore generated ($($enginePaths.Count) engine paths)"

# --- git identity (local to this repo) ---
$gitName = $FullName
if (-not $gitName) { $gitName = git config user.name }
if (-not $gitName) { $gitName = Read-Host "Your full name (for git identity)" }
git config user.name "$gitName"
$gitEmail = $Email
if (-not $gitEmail) { $gitEmail = git config user.email }
if (-not $gitEmail) { $gitEmail = Read-Host "Your work email" }
git config user.email "$gitEmail"

# installation marker (attribution on full-folder copies)
Add-Content -Path (Join-Path $root ".gitignore") -Value "# Installation: $gitName <$gitEmail> $(Get-Date -Format yyyy-MM-dd)"

# --- scaffold: profile note ---
$firstName = $Name
if (-not $firstName) { $firstName = Read-Host "Your first name (used for Brain\<Name>.md)" }
if (-not $firstName) { throw "A first name is required." }
$profile = Join-Path $root "Brain\$firstName.md"
if (Test-Path $profile) {
    Write-Host "[ok] Brain\$firstName.md already exists - left untouched"
} else {
    $template = Get-Content (Join-Path $root "Brain\Templates\user-profile.md") -Raw -Encoding UTF8
    $template = $template -replace '\{\{NAME\}\}', $firstName -replace '\{\{FULL_NAME\}\}', $gitName -replace '\{\{EMAIL\}\}', $gitEmail
    Set-Content -Path $profile -Value $template -Encoding utf8
    Write-Host "[ok] Brain\$firstName.md created from template"
}

# --- scaffold: empty slots + state dirs (never overwrite) ---
$year = (Get-Date).Year
$stubs = @{
    "Brain\Firm.md"              = "# Firm`n`nFirm/team context as YOU need it. Yours to fill.`n"
    "Brain\Decisions\$year.md"   = "---`nyear: $year`n---`n`n# Decisions - $year`n`nAppend-only. Newest first.`n"
}
foreach ($k in $stubs.Keys) {
    $f = Join-Path $root $k
    if (-not (Test-Path $f)) {
        New-Item -ItemType Directory -Force -Path (Split-Path $f) | Out-Null
        Set-Content -Path $f -Value $stubs[$k] -Encoding utf8
        Write-Host "[ok] $k created"
    }
}
foreach ($d in @("Brain\Now\Inbox", "Brain\Now\Archive", "Brain\Clients", "Brain\People", "Brain\Projects", "Brain\Sessions")) {
    New-Item -ItemType Directory -Force -Path (Join-Path $root $d) | Out-Null
}
Write-Host "[ok] state folders ready"

Write-Host ""
Write-Host "Mechanical install complete."
Write-Host "If you are not already inside a /brain-init session: start Claude Code"
Write-Host "from this folder and type /brain-init - it populates your brain from a"
Write-Host "consented scan of your working files plus a short interview."
Write-Host "(Updates later: .brain\update.ps1, or ask Claude to 'run the brain update'.)"
